# Name of this action
name: Jest Automatic Testing

on: pull_request

jobs:

  run-jest-tests:
    name: Jest Tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: ./learn-access-app
        run: npm install

      - name: Run Jest tests
        working-directory: ./learn-access-app
        run: npm test
